import * as THREE from 'https://unpkg.com/three@0.161.0/build/three.module.js';
import {OrbitControls} from 'https://unpkg.com/three@0.161.0/examples/jsm/controls/OrbitControls.js';

const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();}
const initData=tg?.initData||''; const $=id=>document.getElementById(id); let state=null, selected=null, ghost=null, renderer,scene,camera,controls,raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground,clock=new THREE.Clock(); const meshes=new Map();
const colors={house:0xd9a066,apartment:0x9db7c8,shop:0x5d9bd3,school:0xe3c15d,hospital:0xe7e7e7,factory:0x6c7884,business:0x4f91ba,park:0x4a9b62,road:0x343d46};
function api(path,options={}){options.headers={...(options.headers||{}),'Content-Type':'application/json','X-Telegram-Init-Data':initData};return fetch(path,options).then(async r=>{let x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x})}
function mat(c,rough=.8){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:.05})}
function box(g,n,s,p,c){let m=new THREE.Mesh(new THREE.BoxGeometry(...s),mat(c));m.position.set(...p);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
function cyl(g,s,r,h,p,c){let m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,s),mat(c));m.position.set(...p);m.castShadow=true;g.add(m);return m}
function model(kind,level=1){let g=new THREE.Group(), c=colors[kind]||0x8899aa; if(kind==='road'){box(g,'road',[2.9,.05,2.9],[0,.02,0],c);for(let i=-1;i<=1;i+=2)box(g,'line',[.08,.02,2.5],[i*.65,.06,0],0xe9e3bd);return g} if(kind==='park'){box(g,'base',[2.7,.12,2.7],[0,.06,0],0x65a866);for(let x=-.8;x<=.8;x+=.8){cyl(g,8,.13,1.1,[x,.6,0],0x765034);cyl(g,8,.5,.7,[x,1.2,0],0x2f7f4b)}return g} if(kind==='house'){box(g,'body',[1.7,1.1,1.5],[0,.55,0],c);let roof=box(g,'roof',[1.95,.18,1.75],[0,1.25,0],0x774936);roof.rotation.z=.06;box(g,'door',[.25,.5,.04],[0,.35,.77],0x3c271d);for(let x of [-.55,.55])box(g,'window',[.3,.3,.04],[x,.7,.77],0x9bd2e5);return g} if(kind==='shop'){box(g,'body',[2.3,1.4,1.5],[0,.7,0],c);box(g,'roof',[2.45,.15,1.65],[0,1.45,0],0x374c65);box(g,'glass',[1.4,.5,.04],[0,.75,.77],0xb7e4ef);return g} if(kind==='apartment'||kind==='business'){let h=kind==='business'?4.5:3;box(g,'tower',[2, h,1.8],[0,h/2,0],c);for(let y=.6;y<h;y+=.65)for(let x of [-.65,0,.65])box(g,'window',[.25,.22,.04],[x,y,.93],0xbee9ef);box(g,'roof',[2.15,.15,1.95],[0,h+.08,0],0x304456);return g} if(kind==='factory'){box(g,'hall',[2.8,1.7,2.4],[0,.85,0],c);cyl(g,8,.28,2.3,[.8,2,0],0x59636a);cyl(g,8,.25,1.8,[-.8,1.75,0],0x59636a);return g} if(kind==='school'||kind==='hospital'){box(g,'main',[2.8,1.5,2],[0,.75,0],c);box(g,'roof',[3,.16,2.2],[0,1.56,0],kind==='hospital'?0xb94c59:0x4c7397);for(let x of [-.8,0,.8])box(g,'window',[.3,.35,.04],[x,.8,1.02],0x9dd7e6);return g} box(g,'object',[1.5,1.5,1.5],[0,.75,0],c);return g}
function setup(){scene=new THREE.Scene();scene.background=new THREE.Color(0x9cc5d5);scene.fog=new THREE.Fog(0x9cc5d5,35,80);camera=new THREE.PerspectiveCamera(48,1,.1,200);camera.position.set(15,18,18);renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.maxPolarAngle=1.35;controls.minDistance=7;controls.maxDistance=35;scene.add(new THREE.HemisphereLight(0xdcefff,0x496345,2));let sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(10,25,8);sun.castShadow=true;scene.add(sun);ground=new THREE.Mesh(new THREE.PlaneGeometry(48,48),new THREE.MeshStandardMaterial({color:0x668e63,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.userData.ground=true;scene.add(ground);for(let i=-24;i<=24;i+=2){let line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(i,.012,-24),new THREE.Vector3(i,.012,24)]),new THREE.LineBasicMaterial({color:0x6f986a,transparent:true,opacity:.18}));scene.add(line);let line2=line.clone();line2.geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-24,.013,i),new THREE.Vector3(24,.013,i)]);scene.add(line2)} resize();renderer.domElement.addEventListener('pointerdown',onPointer);window.addEventListener('resize',resize);animate()}
function resize(){let r=$('scene').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
function placeMesh(b){let m=model(b.kind,b.level);m.position.set(b.x-11.5,0,b.z-11.5);scene.add(m);meshes.set(b.id,m)}
function renderState(){document.body.classList.add('ready');$('loading').style.display='none';$('cityName').textContent=state.city_name;$('level').textContent='LEVEL '+state.level;$('coins').textContent='₿ '+state.coins.toLocaleString();$('income').textContent='+'+state.income+'/min';for(let m of meshes.values())scene.remove(m);meshes.clear();state.buildings.forEach(placeMesh);renderCatalog()}
function renderCatalog(){let el=$('catalog');el.innerHTML='';Object.entries(state.catalog).forEach(([id,b])=>{let d=document.createElement('div');d.className='item';d.innerHTML=`<div><strong>${b.name}</strong><small>${b.price.toLocaleString()} coins · +${b.income}/min · Level ${b.min_level}</small></div><button ${state.level<b.min_level||state.coins<b.price?'disabled':''}>Select</button>`;d.querySelector('button').onclick=()=>selectBuilding(id);el.appendChild(d)})}
function selectBuilding(id){selected=id;$('buildSheet').classList.add('hidden');if(ghost)scene.remove(ghost);ghost=model(state.catalog[id].kind);ghost.traverse(o=>{if(o.material){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.55}});scene.add(ghost);$('hint').textContent='Tap empty terrain to place '+state.catalog[id].name}
function onPointer(e){if(!selected)return;let r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);let hits=raycaster.intersectObject(ground);if(!hits.length)return;let p=hits[0].point,x=Math.round(p.x+11.5),z=Math.round(p.z+11.5);x=Math.max(0,Math.min(23,x));z=Math.max(0,Math.min(23,z));let c=state.catalog[selected],valid=!state.buildings.some(b=>Math.abs(b.x-x)<c.size[0]&&Math.abs(b.z-z)<c.size[1]);if(!valid){toast('This area is occupied');return}api('/api/build',{method:'POST',body:JSON.stringify({type:selected,x,z})}).then(s=>{state=s;selected=null;if(ghost){scene.remove(ghost);ghost=null}renderState();toast('Building constructed')}).catch(e=>toast(e.message))}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
$('closeBuild').onclick=()=>$('buildSheet').classList.add('hidden');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{let a=b.dataset.action;if(a==='build')$('buildSheet').classList.remove('hidden');if(a==='collect')api('/api/collect',{method:'POST'}).then(x=>{state=x.state;renderState();toast('Collected '+x.collected+' coins')}).catch(e=>toast(e.message));if(a==='upgrade'){let x=state.buildings[state.buildings.length-1];if(x)api('/api/upgrade',{method:'POST',body:JSON.stringify({id:x.id})}).then(s=>{state=s;renderState();toast('Building upgraded')}).catch(e=>toast(e.message))}});
setup();api('/api/state').then(s=>{state=s;renderState()}).catch(e=>{$('loading').textContent=e.message});function animate(){requestAnimationFrame(animate);if(ghost){let t=clock.getElapsedTime();ghost.position.y=Math.sin(t*3)*.04}controls.update();renderer.render(scene,camera)}
